development: &dev
  jetty_port: 8983
  java_opts:
      - "-XX:MaxPermSize=128m"
      - "-Xmx256m"

test: &test
  jetty_port: <%= ENV["TEST_JETTY_PORT"] || '8888' %>
  startup_wait: 45 
  java_opts:
      - "-XX:MaxPermSize=128m"
      - "-Xmx256m"
      
staging: 
  <<: *dev
  
production: 
  <<: *dev
